### ISSUE TITLE
Expose remote search option off el-ui selects

### ISSUE THREAD

**Issue by carsoli** [3YOURMIND/kotti#344]
element-ui supports remote search https://element.eleme.io/#/en-US/component/select#remote-search

Kotti needs to support accepting a `remoteMethod`, to be able to dynamically fetch options based on user query search

### Internal Issues Blocked by This

- https://3yourmind.atlassian.net/browse/B3-7798

**Comment by FlorianWendelborn** [comment]
I think we should consider other solutions for this. The remote search feature that `KtSelect` had was one of the bigger reasons why it grew in complexity. We’d also ideally want a bit more UX around this than just the search itself.

My take on this:

1. Search query should be controlled
2. Search results should be passed via options still
3. There should be a separate loading state for "waiting for backend" interactions (also controlled)

IMO, we should consider having separate components for this, at least to some extend. Alternatives I can think of is exposing a bit more functionality from `KtField*Select` so that we can wrap it in a `KtField*Search` or something like that.

What I want to avoid is increased complexity in usage and implementation, especially given that we still have element UI hacks to worry about already

**Comment by carsoli** [comment]
Closed by the dedicated implementation of `KtFieldSingleSelectRemote` - we don't use element-ui anymore thanks to #565 and so it's closed for the multiselect
