### ISSUE TITLE
Typescript check during build does not work

### ISSUE THREAD

**Issue by Isokaeder** [3YOURMIND/kotti#423]
Typescript errors in `.vue` files do not get picked up on build, pipeline succeeds regardless.

**Comment by FlorianWendelborn** [comment]
Turns out this is because of `@rollup/plugin-typescript` not supporting type checking 🥲

<https://github.com/rollup/plugins/tree/master/packages/typescript#faster-compiling>

Not much we can do here, just the normal perks of the Vue ecosystem. I tried out using `@rollup/plugin-sucrase`, but it fails miserably with handling Vue files as expected.

Once again overwhelmed by the awesomeness of the Vue ecosystem.

**Comment by FlorianWendelborn** [comment]
https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc is another interesting idea
