### ISSUE TITLE
KtTable Always Activates when using Tab

### ISSUE THREAD

**Issue by FlorianWendelborn** [3YOURMIND/kotti#73]
**Describe the bug**
When using an interactive `KtTable`, tabbing through the page will trigger a `activateRow` event (same as a click would). This effectively prevents accessibility entirely instead of helping with accessibility. For example, in AMPI, this means that tabbing through the parts list always opens the first part.

**To Reproduce**
1. Go to any interactive `KtTable`.
2. Tab
3. Notice that the app thinks you’ve clicked

**Expected behavior**
Kotti should only fire such an event if the user actually uses `⏎`.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: 1.5.1

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: 1.5.1

**Additional context**
Here are the lines that are causing the issue: https://github.com/3YOURMIND/kotti/blob/7219b57d84cbb31898e4fc34bc58f134a222febb/packages/kotti-table/src/TableRow.js#L156-L157

**Comment by amrdraz** [comment]
This behaviour was inherited from the older table 
I have no problem removing it 

So what you’re saying that tabling should move through rows and enter should trigger active row

While we’re on the subject is there considerations to be made when the actions slot  is used regarding which action to take ?

**Comment by FlorianWendelborn** [comment]
> While we’re on the subject is there considerations to be made when the actions slot is used regarding which action to take ?

No idea how these are going to work for accessibility. In theory, every `tab` should move to the table row, then first action, then second action, etc..

**Comment by amrdraz** [comment]
ok handling actions sounds like a feature issue outside of the scope of this issue, but let's discuss it none the less.

I assume we would have the actions appear (which I guess they should when a tab is in focused) so that people can still see the actions as they are selected.

Though that said this gets us into a small nick where, so far we allow actions to be set via slot, but in reality people can just put anything, perhaps then we should have a KtTableColumAction component which takes an icon, description and @action  to insure setting the correct markup

otherwise we would still be unable to tab across actions (unless we capture the render output of the slot extending it with aria role and our own things, which is a bit brittle)

**Comment by FlorianWendelborn** [comment]
> I assume we would have the actions appear (which I guess they should when a tab is in focused) so that people can still see the actions as they are selected.

That would be "nice to have", yes.

> Though that said this gets us into a small nick where, so far we allow actions to be set via slot, but in reality people can just put anything, perhaps then we should have a KtTableColumAction component which takes an icon, description and @action to insure setting the correct markup

Buttons should already be tabbable. Are you sure this would be required?
